server:
  port: 13100

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/cloudmp
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.cmp.core.cloud.model, com.cmp.core.user.model
  mapper-locations: classpath:mapping/*.xml